mybatis:
  configuration:
   map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:sqlite:./data/ex_book.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  thymeleaf:
   mode: HTML